[package]
name = "lemmy_db_views"
version = ""
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"

[lib]
doctest = false

[dependencies]
lemmy_db_queries = { version = "=", path = "../db_queries" }
lemmy_db_schema = { version = "=", path = "../db_schema" }
diesel = { version = "1.4.7", features = ["postgres","chrono","r2d2","serde_json"] }
serde = { version = "1.0.129", features = ["derive"] }
log = "0.4.14"
url = "2.2.2"

[dev-dependencies]
serial_test = "0.5.1"
