[package]
name = "lemmy_routes"
version = "0.16.5"
edition = "2021"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
lemmy_utils = { version = "=0.16.5", path = "../utils" }
lemmy_websocket = { version = "=0.16.5", path = "../websocket" }
lemmy_db_views = { version = "=0.16.5", path = "../db_views" }
lemmy_db_views_actor = { version = "=0.16.5", path = "../db_views_actor" }
lemmy_db_schema = { version = "=0.16.5", path = "../db_schema" }
lemmy_api_common = { version = "=0.16.5", path = "../api_common" }
lemmy_apub = { version = "=0.16.5", path = "../apub" }
diesel = "2.0.0"
actix-web = { version = "4.2.1", default-features = false, features = ["rustls"] }
anyhow = "1.0.65"
chrono = { version = "0.4.22", features = ["serde"], default-features = false }
futures = "0.3.24"
reqwest = { version = "0.11.12", features = ["stream"] }
reqwest-middleware = "0.1.6"
rss = "2.0.1"
serde = { version = "1.0.145", features = ["derive"] }
url = { version = "2.3.1", features = ["serde"] }
strum = "0.24.1"
once_cell = "1.15.0"
tracing = "0.1.36"
tokio = { version = "1.21.1", features = ["sync"] }
