[package]
name = "lemmy_utils"
version = "0.16.5"
edition = "2021"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"
rust-version = "1.57"

[lib]
name = "lemmy_utils"
path = "src/lib.rs"
doctest = false

[dependencies]
regex = "1.6.0"
chrono = { version = "0.4.22", features = ["serde", "clock"], default-features = false }
lettre = "0.10.1"
tracing = "0.1.36"
tracing-error = "0.2.0"
itertools = "0.10.5"
rand = "0.8.5"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = { version = "1.0.85", features = ["preserve_order"] }
comrak = { version = "0.14.0", default-features = false }
once_cell = "1.15.0"
openssl = "0.10.41"
url = { version = "2.3.1", features = ["serde"] }
actix-web = { version = "4.2.1", default-features = false, features = ["rustls"] }
anyhow = "1.0.65"
reqwest-middleware = "0.1.6"
strum = "0.24.1"
strum_macros = "0.24.3"
futures = "0.3.24"
diesel = { version = "2.0.0", features = ["chrono"] }
http = "0.2.8"
deser-hjson = "1.0.2"
smart-default = "0.6.0"
jsonwebtoken = "8.1.1"
doku = { version = "0.12.0", features = ["url-2"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
html2text = "0.4.2"
rosetta-i18n = "0.1.2"
parking_lot = "0.12.1"

[build-dependencies]
rosetta-build = "0.1.2"
